### ISSUE TITLE
Stream saving default filename: Wrong time, colon

### ISSUE THREAD

**Issue by mkomko** [tonycpsu/mlbstreamer#19]
I have two issues with the new default filename. Example: `mlb.2018-03-31.nyy@tor.20:07.yes.ts`

1. The time is wrong. The game started at 4:07pm or 16:07 local/game time and 10:07pm or 22:07 my time. I guess it is UTC. I would suggest eastern time, since MLB uses that.
2. A colon is not allowed as part of a filename on Windows.

Maybe: `mlb.2018-03-31.nyy@tor.4.07p.yes.ts`
I don't know, the time in the filename looks weird :-).

BTW: Happy easter everyone and especially @tonycpsu!

**Comment by snipem** [comment]
Since you're also placed in Europe maybe we should discuss timezones. I would prefer the command line tool `play.py` to work on US/Eastern while the GUI should also be able to show times in the local time zone and also in military time. Depending on the users locale.

**Comment by mkomko** [comment]
Sounds good to me, let's see what tonycpsu thinks.

**Comment by tonycpsu** [comment]
Aiieee, I've been away from Windows for so long that I forgot about the colon thing.  Stupid DOS with its fake pipes.  :)

I'll probably just go with `hhmm` (24-hour format), but Eastern time makes sense, yeah.

As for times displayed in the `mlbstreamer` GUI, that's controlled by the `time_zone` variable in `config.yaml`, and still seems to work for me.

**Comment by snipem** [comment]
So why do you persist the timezone in the first place? Isn't this something that can be easily taken from the users locale?

**Comment by tonycpsu** [comment]
@snipem: It actually does detect the system's local time zone during setup and uses that by default.

The point of making it configurable was for folks who'd prefer to keep it in their "home" time zone when traveling, or just want to keep the display in US/Eastern wherever they are.

It wouldn't be hard to have it detect the local zone each time it runs, but it sometimes does introduce a delay of a second or two.  If this is important to you, file a new issue and I'll see what I can do.
