### ISSUE TITLE
Allow saving the stream to a file

### ISSUE THREAD

**Issue by mkomko** [tonycpsu/mlbstreamer#3]
I saw that streamlink supports it and a parameter is already added to mlbplay. The relevant code is commented out, however.

If this feature is not wanted please feel free to close or delete the issue.

I propose:
- Enabling the feature/parameter.
- Adding a second feature/parameter to save the stream to a file with a sensible name, like date.awayteam.hometeam.network.resolution-league-gameno.ext, e.g. 20180101.bos.nyy.yes.720p-mlb-1.mp4. The "gameno" is useful for doubleheaders. Or even another parameter for the name format.

If nobody wants to tackle the feature I will for sure give it a shot sometime down the line and might be able to do a pull request. But I'm a Java/.NET developer first and foremost, so Python is not my forte. I want this feature though, since I usually watch on a different device.

**Comment by mkomko** [comment]
@tonycpsu What do you think about my proposals? I might give it a go in the near future if you like them.

**Comment by tonycpsu** [comment]
It's a fine idea, and as you suggested, it already saves the stream if you un-comment the `-o` argument, so the general idea was on my radar.  I already did something similar with the file naming scheme you suggested with a wrapper script around daftcat's mlbplay before, so it'd just be a matter of grafting that into mlbstreamer.

However, I won't get my MLB.tv account again until 2018-03-27, so if this is something you wanted right away, you could give it a go.  It's definitely something I'll be doing, as my own workflow is usually saving games and watching them later, not streaming live.

**Comment by mkomko** [comment]
Thanks for your fast reply! Since it's something you'll be doing anyway I will let you go ahead. I'm sure you'll be faster and it'll be easier for you :-). I'm looking forward to this and the season! Thanks.

**Comment by tonycpsu** [comment]
I just pushed a partial implementation of this that saves to a file, though the default filename isn't very useful at the moment.  Will work on better default filename with teams, start time, etc. later.

**Comment by sdelafond** [comment]
-s /path/to/file.ogg indeed does work fine for me.

**Comment by mkomko** [comment]
I added a pull request (#17) to add some more information to the default filename.

**Comment by tonycpsu** [comment]
Looks great.  I improved on the idea bit in eab36bf0358013af30da8719eb7d8511e4971c1d to support using a user-provided directory name with the default filename, so I think this one's pretty much complete.
