### ISSUE TITLE
NHL ?

### ISSUE THREAD

**Issue by jgshier** [tonycpsu/mlbstreamer#36]
Any chance you will add NHL to this?

**Comment by tonycpsu** [comment]
I seem to recall that MLB and NHL are both hosted on the same MLBAM platform, but I haven't dug that deeply into it.  If the infrastructure is the same, it shouldn't be too heavy a lift.

I haven't been an NHL.tv subscriber for many years, though, and I don't think I'd get enough use out of it to make it worth paying for.  If enough people were interested, maybe I could set up a Patreon or something.

**Comment by tonycpsu** [comment]
I seem to recall that MLB and NHL are both hosted on the same MLBAM platform, but I haven't dug that deeply into it. If the infrastructure is the same, it shouldn't be too heavy a lift.

I haven't been an NHL.tv subscriber for many years, though, and I don't think I'd get enough use out of it to make it worth paying for. If enough people were interested, maybe I could set up a Patreon or something to cover the cost of a single-team package.

**Comment by tonycpsu** [comment]
Hm, actually, it looks like NHL.tv offered some free games each week last year.  I'll keep an eye out to see if they do that this year.  If so, I wouldn't need to subscribe to be able to add NHL support.

**Comment by jgshier** [comment]
Well I would be willing to pay for a sub for you...

**Comment by tonycpsu** [comment]
Played around with this a bit last night using the free stream of the day.  Should be doable.

The authentication sequence is totally different, and I'm running into "too many usage attempts" errors as I develop and debug my way to something that works, but I feel like I'm pretty close.

**Comment by jgshier** [comment]
sounds good!

**Comment by tonycpsu** [comment]
NHL.tv should now be supported by the new [streamglob](https://github.com/tonycpsu/streamglob/) application, which supersedes `mlbstreamer`.  Please direct any issues with NHL.tv support to that project.
